### ISSUE TITLE
API doesn't load on WB network

### ISSUE THREAD

**Issue by olafveerman** [WorldBank-Transport/ram-backend#158]
The staging environment doesn't work on the WB network:

![screenshot from 2017-07-13 10-17-27](https://user-images.githubusercontent.com/751330/28372589-1f3cbb02-6c6e-11e7-9088-2c95bbe9ea73.png)

> 234.207.194.24:4000/projects Failed to load resource: the server responded with a status of 503 (Service Unavailable)
/#/en/:1 Fetch API cannot load http://34.207.194.24:4000/projects. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://rra-staging.s3-website-us-east-1.amazonaws.com' is therefore not allowed access. The response had HTTP status code 503. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

cc @danielfdsilva

**Comment by danielfdsilva** [comment]
Changed the api port to 80, let's see if it solves the problem.

**Comment by olafveerman** [comment]
This is mostly due to firewall restrictions of the Bank. The current domain is not white-listed, which obliges people to go to the API and click a `continue` button.
