### ISSUE TITLE
Import road network from OSM

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/ram-backend#163]
From #157 

Importing data from OSM only works for very small bounding boxes. We should look into other options/services that allow us to get the same data

**Comment by kamicut** [comment]
@danielfdsilva can this be done as a separate process and [osmfilter](https://wiki.openstreetmap.org/wiki/Osmfilter)? What should the output format be?

**Comment by danielfdsilva** [comment]
This was handled here https://github.com/WorldBank-Transport/ram-backend/pull/165.

Leaving it open until further testing is done.

**Comment by olafveerman** [comment]
Closing this issue. We can open a new thread if more specific issues arise.
