### ISSUE TITLE
Data export form osm-p2p

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/ram-backend#185]
I've encountered a very strange behavior with iD and osm-p2p. It's a bit complicated to explain so please bear with me.

With iD I to create the following road:
![image](https://user-images.githubusercontent.com/1090606/30748448-3cae1254-9fa8-11e7-8d39-30c965c81f50.png)

I then export the the data to `xml` format for the whole world (`-180,-90,180,90`) and it shows up well:
```
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="obj2osm">
    <bounds minlon="-180" minlat="-90" maxlon="180" maxlat="90"/>
    <node lon="-37.67837980274526" lat="-10.915534254726065" changeset="4494256649682866880" timestamp="2017-09-22T13:51:54.003Z" id="11471841636528404556" version="230c2a76c3d25ea23ebc65fec43ad0132abc8511a23bf36042d21486ff8abbce"/>
    <node lon="-37.669798821311154" lat="-10.90864397569923" changeset="4494256649682866880" timestamp="2017-09-22T13:51:54.003Z" id="6189487012002221839" version="21cee350a95281696d89f0279bc7ddfba1ef0030a34921132713fd10c4dfaf48"/>
    <node lon="-37.65969411420185" lat="-10.915416137002952" changeset="4494256649682866880" timestamp="2017-09-22T13:51:54.003Z" id="13521463535618753104" version="783a402a844eb678c335779e578022b6e8bd2fc39d83b804e2d18376a72cd701"/>
    <way changeset="14629516051797836493" timestamp="2017-09-22T14:15:36.785Z" id="15172602618370998525" version="33b868e561bc15f69a64a4a6c5aaa0ebbc192989a0c3cea9dea0538ce545dd4c">
        <nd ref="11471841636528404556"/>
        <nd ref="6189487012002221839"/>
        <nd ref="13521463535618753104"/>
        <tag k="highway" v="tertiary"/>
    </way>
</osm>
```

Then I proceed to add a new road that connects to the first one:
![image](https://user-images.githubusercontent.com/1090606/30748905-a38c1416-9fa9-11e7-8881-3c11f2bc7942.png)

And this is what iD sends to the changeset upload endpoint:
```
<?xml version="1.0" encoding="UTF-8"?>
<diffResult version="0.6" generator="obj2osm">
    <node old_id="-1" new_id="10507597692561999554" new_version="bbd775f7166885d2ff33b0b9de3caf36452b1e2901d70eb0a12bc0f944764603"/>
    <node old_id="-2" new_id="2647234077267737547" new_version="2868cc7e046c876563df0872325975a081f7283c36dad1bd4177a8ac43d8468c"/>
    <way old_id="-1" new_id="885636361779102127" new_version="6fdebcdf28f55f67dcf400bd354d9c68f034592a86083fd1c064de689a53d710"/>
    <way old_id="15172602618370998525" new_id="15172602618370998525" new_version="d0d8689310d9558e0bd63ddfe4a7bf8a413f2cb5369d7b1662cc9d7adfdf8e6e"/>
</diffResult>
```
Seems all fine so far. However when I export again for the whole world and look at the exported osm data, this new way is missing. The two new nodes are there, but the way is not.

```
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="obj2osm">
    <bounds minlon="-180" minlat="-90" maxlon="180" maxlat="90"/>
    <node lon="-37.65969411420185" lat="-10.915416137002952" changeset="4494256649682866880" timestamp="2017-09-22T13:51:54.003Z" id="13521463535618753104" version="783a402a844eb678c335779e578022b6e8bd2fc39d83b804e2d18376a72cd701"/>
    <node lon="-37.67466764005293" lat="-10.912553515436214" changeset="4824823130905102639" timestamp="2017-09-22T14:19:24.645Z" id="10507597692561999554" version="bbd775f7166885d2ff33b0b9de3caf36452b1e2901d70eb0a12bc0f944764603"/>
    <node lon="-37.66364896707162" lat="-10.912765618234246" changeset="4824823130905102639" timestamp="2017-09-22T14:19:24.645Z" id="2647234077267737547" version="2868cc7e046c876563df0872325975a081f7283c36dad1bd4177a8ac43d8468c"/>
    <node lon="-37.67837980274526" lat="-10.915534254726065" changeset="4494256649682866880" timestamp="2017-09-22T13:51:54.003Z" id="11471841636528404556" version="230c2a76c3d25ea23ebc65fec43ad0132abc8511a23bf36042d21486ff8abbce"/>
    <node lon="-37.669798821311154" lat="-10.90864397569923" changeset="4494256649682866880" timestamp="2017-09-22T13:51:54.003Z" id="6189487012002221839" version="21cee350a95281696d89f0279bc7ddfba1ef0030a34921132713fd10c4dfaf48"/>
    <way changeset="4824823130905102639" timestamp="2017-09-22T14:19:24.645Z" id="15172602618370998525" version="d0d8689310d9558e0bd63ddfe4a7bf8a413f2cb5369d7b1662cc9d7adfdf8e6e">
        <nd ref="11471841636528404556"/>
        <nd ref="10507597692561999554"/>
        <nd ref="6189487012002221839"/>
        <nd ref="2647234077267737547"/>
        <nd ref="13521463535618753104"/>
        <tag k="highway" v="tertiary"/>
    </way>
</osm>
```

**This is a problem because if the way is not in the `xml` file, I won't be able to generate the correct vector tiles, and `OSRM` won't use it for the routing**

It gets even stranger when I reopen iD and zoom to that area.
![image](https://user-images.githubusercontent.com/1090606/30749577-bd0bc768-9fab-11e7-905f-2cfd847c34b7.png)
One of the request iD makes to the `/map` endpoint include that way, but the full export doesn't.

Questions:
- Why does the way show up in iD but not on the full export?
- Is there some sort of simplification going on?

**Comment by danielfdsilva** [comment]
I've been running a few more tests to try to understand what is happening. I was able to figure out when it works and when it doesn't but the why still evades me.

I tried and visualized different bounding boxes to see what was the difference between when it worked vs when it didn't.

Here is the roads and two requests with different bounding boxes that iD makes.
- The green one returns the correct export, in this case being the 2 roads.
- The orange one only return the data for the long road.

![image](https://user-images.githubusercontent.com/1090606/30819065-7c7aacca-a215-11e7-84e7-3b06a080d7d6.png)

I then tried with some weirder bounding boxes to see what the behavior was:
- `yellow` - Returns data correctly
- `blue` - Only returns the long road
- `violet` - Doesn't return anything

![image](https://user-images.githubusercontent.com/1090606/30819329-4a88d718-a216-11e7-9e6b-4217e2530d6b.png)

### Conclusion ?
It must have something to do with the points that are inside the bounding box. In the `violet` case there are no points directly inside it so nothing gets returned.
In the `green` case there's a common point between the long and short roads, so both get returned.
I don't understand the behavior of the `blue` and `orange` cases. They both contain more than one point but only the long road is returned. Could it be that the system sees the point as belonging to the long road and doesn't check anything else?

**Comment by noffle** [comment]
You have found a legit bug in [osm-p2p-db](https://github.com/digidem/osm-p2p-db)! I now have a reproducing unit test. The query & collect algorithm assumed that multiple ways wouldn't share nodes *and* those nodes would be proper subsets of another way.

**Comment by noffle** [comment]
@danielfdsilva fixed in https://github.com/digidem/osm-p2p-db/pull/58. could you update osm-p2p-db to latest and see if you can reproduce?

**Comment by danielfdsilva** [comment]
@noffle Works great! thanks for the quick fix! 🥇
