### ISSUE TITLE
Profile file editor

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/ram-backend#228]
The profile editor allows users to customize the profile used by OSRM through an interface. Updating the Lua file directly has proven to be overwhelming and error prone for non-technical users. The interface should make it easier to adapt the most important settings to the local context of a project.

The editor focuses on speed limits for different tags. For more advanced customization, users can still upload a custom Lua file with the profile.

The profile is traversal to a project, so editing it will affect all the scenarios of the project.

A default OSRM profile file for a car can be see [here](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua)

Below are listed the specs of this feature, together with a brief explanation of how the profile works for context.

## Frontend
From the project page it must be possible to open a modal with a form to edit the speed values (likely through a button near the profile file).
The form needs to allow the user to edit the following speed values:
```
speeds
surface_speeds  (tag: surface)
tracktype_speeds  (tag: tracktype)
smoothness_speeds  (tag: smoothness)
maxspeed_table_default (tag: maxspeed:advisory|maxspeed)
maxspeed_table (tag: maxspeed:advisory|maxspeed)
```

**speeds**
The speeds are defined per tag and value. It is possible to define speeds for different tag-value pairs. Ex:
```
highway
  motorway   = 90
  primary    = 100
amenity
  parking   = 10
```
The form element for the speeds would look something like:
![image](https://user-images.githubusercontent.com/1090606/42180062-b758f9ec-7e2d-11e8-87b0-860ebf8cc31f.png)

**surface_speeds**
The surface speeds will check the value of the `surface` tag only and depending on its value attribute a speed, therefore this will be a simple key value form.

![image](https://user-images.githubusercontent.com/1090606/42180074-c1ce2dc0-7e2d-11e8-844b-11018d1a2dd1.png)

**tracktype_speeds**
Works the same way as `surface_speeds` but for the `tracktype` tag.

**smoothness_speeds**
Works the same way as `surface_speeds` but for the `smoothness` tag.

**maxspeed**
Which maxspeed definition is used (`maxspeed_table_default` or `maxspeed_table`) depends on what sort of value the tag `maxspeed:advisory` or `maxspeed` has (whichever of these 2 appears first).
- If the tag has a numeric value then that is assumed.
- If the tag has a string value it searches for it in the `maxspeed_table_default` which typically defines speeds by zone (rural, urban, etc).
- If the tag has a string value but it is not found in the `maxspeed_table_default` it assumes it is a special case that depends on country and looks for it in the `maxspeed_table`. Here it should have a value of <countrycode>:<zone type> (ex: "ch:rural")

Not sure what the best way to design this piece because these values need to be separated programmatically but they represent the same.

@ricardomestre over to you for the design of the form, now that we have a clearer idea of what is needed.

## Backend
The backend needs to have an API to power this:

**GET /projects/{projId}/profile**
Should load the profile, parse the values and return a response with the values needed by the form.
Steps:
  - Perform basic checks (projects exists, setup is finalized, etc)
  - Check the `projects_files` table for the file
  - Get the file from the storage
  - Parse the contents and prepare response

**POST /projects/{projId}/profile**
Should validate the submitted values and update the profile file correctly.
Steps:
  - Perform basic checks (projects exists, setup is finalized, etc)
  - Validate submitted data
  - Check the `projects_files` table for the file
  - Get the file from the storage
  - Update the file content with new values.
  - Store file
  - Update DB

Questions:
- Should we allow customization of custom profile files?
- What happens if we can't parse it?

---

# Structure of the speeds in a profile file

> Originally posted on slack

I did some investigation on the speeds defined in the profile. There are 6 variables about speeds (I’m not considering penalties here).
```
speeds
surface_speeds
tracktype_speeds
smoothness_speeds
maxspeed_table_default
maxspeed_table
```

The script starts by looking at the `speeds` variable. This one defines speeds based on tag and value like:
```
speeds = Sequence {
  highway = {
    motorway        = 90 ...
  }
}
```
This means that when looking for a speed it will search the way for a tag named `highway` with a value that falls in the options defined. In the current profile file only the `highway` tag is considered but it would be possible to look for other tags as well. Fox example:
```
speeds = Sequence {
  highway = {
    motorway        = 90 ...
  },
  amenity = {
    parking         = 10 ...
  }
}
```
Since `speeds` is a `Sequence` the search would be done in order and stop at the first match. So if a `highway` tag is found there would be no need to search for `amenity`.

After the tag based speed is found it looks, in sequence, at:
- `surface_speeds`
- `tracktype_speeds`
- `smoothness_speeds`
And the minimum value is kept.

The last step is to look at the `maxspeed_table_default` or `maxspeed_table` and again check the minimum value.

**Comment by danielfdsilva** [comment]
@vgeorge I'm not completely understanding the need for the `script` property. Why can't it be sent to the client in json format, populate the form and then bevsent back to the server also in json, and create the file from that?

**Comment by vgeorge** [comment]
Do you mean in `POST` requests? This property is only available when type is `custom`, which means the client is trying to send a read-only Lua script. If the user is posting data to fill a template, the `script` is ignored, because only `templateData` is needed to generate the script from the a template.

In `GET` requests, the `script` property always contains a lua script, either a custom file or generated from a template. Script generation from template has to be centralized on the server, that way we avoid code repetition and unneeded dependencies in the client. I don't know yet how `ram-analisys` gets the script prepare the network, but it will also not need a template engine if the backend generates it.

**Comment by danielfdsilva** [comment]
Implemented
