### ISSUE TITLE
Profile editor api

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/ram-backend#229]
Implement editor api according to the specs on https://github.com/WorldBank-Transport/ram-backend/issues/228

**Comment by vgeorge** [comment]
I've uploaded the profile generator to a gist:

https://gist.github.com/vgeorge/3e229acdbc61dba39233d3086d1679a1

To test locally, just copy to a directory and run `yarn` and `yarn start`. It will generate a lua profile from the object inside of `index.js`. The generator has a function `.toLua` that transforms a JSON object to a Lua table and a string literal which uses that function to generate a lua file. The resulting string is formatted using `lua-fmt` package, which checks for its sanity and make it prettier.

**Comment by danielfdsilva** [comment]
Implemented
